using System.Text;
using PPSHGram.Telegram.CodeGen.Schema;

namespace PPSHGram.Telegram.CodeGen.CSharp;

internal static class CSharpTypeWriter
{
    public static string WriteType(TelegramType type)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine();
        builder.AppendLine("namespace PPSHGram.Telegram.Generated.Types;");
        builder.AppendLine();
        CSharpXmlDocs.WriteSummary(builder, type.Description);
        builder.AppendLine($"public sealed partial class {type.Name}");
        builder.AppendLine("{");

        foreach (var field in type.Fields)
        {
            WriteProperty(builder, type.Name, field);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    public static string WritePlaceholderType(string typeName)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace PPSHGram.Telegram.Generated.Types;");
        builder.AppendLine();
        CSharpXmlDocs.WriteSummary(builder, $"Represents the Telegram Bot API {typeName} type.");
        builder.AppendLine($"public partial class {typeName}");
        builder.AppendLine("{");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void WriteProperty(StringBuilder builder, string containingTypeName, TelegramField field)
    {
        var csharpType = CSharpTypeMapper.Map(field.Type, field.Required);
        var propertyName = CSharpNaming.ToPropertyName(field.Name, containingTypeName);
        var initializer = CSharpTypeMapper.NeedsDefaultInitializer(csharpType, field.Required) ? " = default!;" : string.Empty;

        CSharpXmlDocs.WriteSummary(builder, field.Description, 4);
        builder.AppendLine($"    [JsonPropertyName(\"{field.Name}\")]");
        builder.AppendLine($"    public {csharpType} {propertyName} {{ get; init; }}{initializer}");
        builder.AppendLine();
    }
}
