using System.Text;
using PPSHGram.Telegram.CodeGen.Schema;

namespace PPSHGram.Telegram.CodeGen.CSharp;

internal static class CSharpApiWriter
{
    public static string WriteApi(IEnumerable<TelegramMethod> methods)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Net.Http;");
        builder.AppendLine("using System.Text.Json;");
        builder.AppendLine("using PPSHGram.Telegram.Client;");
        builder.AppendLine("using PPSHGram.Telegram.Generated.Methods;");
        builder.AppendLine("using PPSHGram.Telegram.Generated.Requests;");
        builder.AppendLine();
        builder.AppendLine("namespace PPSHGram.Telegram;");
        builder.AppendLine();
        CSharpXmlDocs.WriteSummary(builder, "Typed Telegram Bot API client.");
        builder.AppendLine("public sealed partial class Api : TelegramApiClient");
        builder.AppendLine("{");
        builder.AppendLine("    public Api(");
        builder.AppendLine("        string token,");
        builder.AppendLine("        HttpClient? httpClient = null,");
        builder.AppendLine("        Uri? baseAddress = null,");
        builder.AppendLine("        JsonSerializerOptions? jsonSerializerOptions = null)");
        builder.AppendLine("        : base(token, httpClient, baseAddress, jsonSerializerOptions)");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();

        foreach (var method in methods.OrderBy(method => method.Name, StringComparer.Ordinal))
        {
            WriteMethod(builder, method);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void WriteMethod(StringBuilder builder, TelegramMethod method)
    {
        var methodName = CSharpNaming.ToPascalCase(method.Name);
        var requestName = $"{methodName}Request";
        var returnType = QualifyReturnType(CSharpTypeMapper.Map(method.ReturnType, required: true));

        CSharpXmlDocs.WriteSummary(builder, method.Description, 4);
        CSharpXmlDocs.WriteParameterRemarks(
            builder,
            method.Parameters.Select(parameter => (parameter.Name, parameter.Type, parameter.Required, parameter.Description)),
            4);
        builder.AppendLine($"    public Task<{returnType}> {methodName}(");
        builder.AppendLine($"        {requestName} request,");
        builder.AppendLine("        CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine($"        return CallAsync<{returnType}>(TelegramMethods.{methodName}, request, cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static string QualifyReturnType(string csharpType)
    {
        const string listPrefix = "IReadOnlyList<";

        if (csharpType.StartsWith(listPrefix, StringComparison.Ordinal) && csharpType.EndsWith(">", StringComparison.Ordinal))
        {
            var inner = csharpType[listPrefix.Length..^1];
            return $"{listPrefix}{QualifyReturnType(inner)}>";
        }

        return IsGeneratedType(csharpType)
            ? $"PPSHGram.Telegram.Generated.Types.{csharpType}"
            : csharpType;
    }

    private static bool IsGeneratedType(string csharpType)
    {
        return csharpType is not "object"
            and not "string"
            and not "long"
            and not "int"
            and not "double"
            and not "bool"
            && csharpType.Length > 0
            && char.IsUpper(csharpType[0]);
    }
}
