using System.Text;
using PPSHGram.Telegram.CodeGen.Schema;

namespace PPSHGram.Telegram.CodeGen.CSharp;

internal static class CSharpRequestWriter
{
    public static string WriteRequest(string requestName, TelegramMethod method)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine("using PPSHGram.Telegram.Generated.Types;");
        builder.AppendLine();
        builder.AppendLine("namespace PPSHGram.Telegram.Generated.Requests;");
        builder.AppendLine();
        CSharpXmlDocs.WriteSummary(builder, method.Description);
        CSharpXmlDocs.WriteParameterRemarks(
            builder,
            method.Parameters.Select(parameter => (parameter.Name, parameter.Type, parameter.Required, parameter.Description)));
        builder.AppendLine($"public sealed partial class {requestName}");
        builder.AppendLine("{");

        foreach (var parameter in method.Parameters)
        {
            WriteProperty(builder, requestName, parameter);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void WriteProperty(StringBuilder builder, string containingTypeName, TelegramField parameter)
    {
        var csharpType = CSharpTypeMapper.Map(parameter.Type, parameter.Required);
        var propertyName = CSharpNaming.ToPropertyName(parameter.Name, containingTypeName);
        var initializer = CSharpTypeMapper.NeedsDefaultInitializer(csharpType, parameter.Required) ? " = default!;" : string.Empty;

        CSharpXmlDocs.WriteSummary(builder, parameter.Description, 4);
        builder.AppendLine($"    [JsonPropertyName(\"{parameter.Name}\")]");
        builder.AppendLine($"    public {csharpType} {propertyName} {{ get; init; }}{initializer}");
        builder.AppendLine();
    }
}
