using System.Text;
using PPSHGram.Telegram.CodeGen.Schema;

namespace PPSHGram.Telegram.CodeGen.CSharp;

internal static class CSharpMethodsWriter
{
    public static string WriteMethods(IEnumerable<TelegramMethod> methods)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace PPSHGram.Telegram.Generated.Methods;");
        builder.AppendLine();
        CSharpXmlDocs.WriteSummary(builder, "Telegram Bot API method names.");
        builder.AppendLine("public static partial class TelegramMethods");
        builder.AppendLine("{");

        foreach (var method in methods.OrderBy(method => method.Name, StringComparer.Ordinal))
        {
            CSharpXmlDocs.WriteSummary(builder, method.Description, 4);
            CSharpXmlDocs.WriteParameterRemarks(
                builder,
                method.Parameters.Select(parameter => (parameter.Name, parameter.Type, parameter.Required, parameter.Description)),
                4);
            builder.AppendLine($"    public const string {CSharpNaming.ToPascalCase(method.Name)} = \"{method.Name}\";");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }
}
